appName: secure-finance

image:
  backend:
    repository: myregistry01secure.azurecr.io/secure-backend
    tag: v1-amd64
    pullPolicy: Always
  frontend:
    repository: myregistry01secure.azurecr.io/secure-frontend
    tag: v1-amd64
    pullPolicy: Always

service:
  backendPort: 5001
  frontendPort: 80

ingress:
  host: secureapp.135.235.225.3.nip.io
  className: nginx

keyvault:
  name: key-vault-01-secure
  clientId: 37669721-0f3a-4857-ab78-b04ba98adb5f
  tenantId: 29d6b2c1-5a07-49dc-ad3b-a84fe545e6d9

tls:
  email: bhanuja@example.com
  issuerName: letsencrypt-prod
