# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-secrets
# type: Opaque
# data:
#   AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXN0b3JhZ2UxMmFjY291bnQxMDtBY2NvdW50S2V5PWxaRjJkcXloRFVueURIQlhZbVlPWVR2NFM2RDNwaE05bkJlanY3TWdnQWNtMXNhVHdZVGdTWUhXTWNTb3ZrdTdwWEVkNkQ5OXpGMC8rQVN0LzAwVTlnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
#   JWT_SECRET: QWkrVEtOUjN6VWxhaFV2Y3RrNlc2Y2RiQTFWVnpmUktDTnlqZ1cxckFJTnhYQWNHZzMyS0xLVXpzWUx3UUZjSA==

# azure-secrets-spc.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "37669721-0f3a-4857-ab78-b04ba98adb5f"
    keyvaultName: "key-vault-01-secure"
    objects: |
      array:
        - objectName: AZURE_STORAGE_CONNECTION_STRING
          objectType: secret
        - objectName: JWT_SECRET
          objectType: secret
    tenantId: "29d6b2c1-5a07-49dc-ad3b-a84fe545e6d9"
