apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyvault.clientId }}"
    keyvaultName: "{{ .Values.keyvault.name }}"
    tenantId: "{{ .Values.keyvault.tenantId }}"
    objects: |
      array:
        - objectName: AZURE_STORAGE_CONNECTION_STRING
          objectType: secret
        - objectName: JWT_SECRET
          objectType: secret
