apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: azure
  secretObjects:
    - secretName: azure-storage-secret
      type: Opaque
      data:
        - objectName: AZURE-STORAGE-CONNECTION-STRING
          key: AZURE_STORAGE_CONNECTION_STRING
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "37669721-0f3a-4857-ab78-b04ba98adb5f"
    keyvaultName: "key-vault-01-secure"
    tenantId: "29d6b2c1-5a07-49dc-ad3b-a84fe545e6d9"

    objects: |
      array:
        - |
          objectName: AZURE-STORAGE-CONNECTION-STRING
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
