apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: {{ .Values.appName }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
  type: ClusterIP
