apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: {{ .Values.appName }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
  type: ClusterIP
