apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXN0b3JhZ2UxMmFjY291bnQxMDtBY2NvdW50S2V5PWxaRjJkcXloRFVueURIQlhZbVlPWVR2NFM2RDNwaE05bkJlanY3TWdnQWNtMXNhVHdZVGdTWUhXTWNTb3ZrdTdwWEVkNkQ5OXpGMC8rQVN0LzAwVTlnPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  JWT_SECRET: QWkrVEtOUjN6VWxhaFV2Y3RrNlc2Y2RiQTFWVnpmUktDTnlqZ1cxckFJTnhYQWNHZzMyS0xLVXpzWUx3UUZjSA==
